// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSK2HHUSvQaUVb0F5sLEdVmuWtFwuDiFk',
    appId: '1:875809051038:web:e4c46f3783d849cf2bc68f',
    messagingSenderId: '875809051038',
    projectId: 'ripple-cb017',
    authDomain: 'ripple-cb017.firebaseapp.com',
    storageBucket: 'ripple-cb017.appspot.com',
    measurementId: 'G-1F040H23YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArOY5WiYy1TjRRnPwRpxGgytAR4MKU3Hs',
    appId: '1:875809051038:android:d75ec9a249ab27872bc68f',
    messagingSenderId: '875809051038',
    projectId: 'ripple-cb017',
    storageBucket: 'ripple-cb017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZfyrc02ZaBSVufUTdJLFOni3MD5Hi5U',
    appId: '1:875809051038:ios:89192db347c695c62bc68f',
    messagingSenderId: '875809051038',
    projectId: 'ripple-cb017',
    storageBucket: 'ripple-cb017.appspot.com',
    iosBundleId: 'com.ripple.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzZfyrc02ZaBSVufUTdJLFOni3MD5Hi5U',
    appId: '1:875809051038:ios:f5d7d4eedf71c3172bc68f',
    messagingSenderId: '875809051038',
    projectId: 'ripple-cb017',
    storageBucket: 'ripple-cb017.appspot.com',
    iosBundleId: 'com.example.familyGameNight',
  );
}
